# Aula 1 - An√°lise de Dados com Pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [3]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [5]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [6]:
df.shape

(133349, 11)

In [7]:
var1, colunas = df.shape[0], df.shape[1]
print("linhas:", var1)
print("colunas:", colunas)

linhas: 133349
colunas: 11

In [25]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [29]:
renomear_colunas ={
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

df.rename(columns=renomear_colunas, inplace=True)
df.columns

Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [31]:
df["senioridade"].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [32]:
df["contrato"].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [33]:
df["remoto"].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [34]:
df["tamanho_empresa"].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [35]:
senioridade = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}

df['senioridade'] = df["senioridade"].replace(senioridade)
df["senioridade"].value_counts()

senioridade
Senior       77241
Pleno        40465
Junior       12443
Executivo     3200
Name: count, dtype: int64

In [36]:
contrato = {
    'FT': 'Integral',
    'PT': 'Parcial',
    'FL': 'Freelancer',
    'CT': 'Contrato'
}

df["contrato"] = df["contrato"].replace(contrato)
df["contrato"].value_counts()

contrato
Integral      132563
Contrato         394
Parcial          376
Freelancer        16
Name: count, dtype: int64

In [37]:
tamanho_empresa = {
    'S': 'Pequena',
    'M': 'Media',
    'L': 'Grande'
}

df["tamanho_empresa"] = df["tamanho_empresa"].replace(tamanho_empresa)
df["tamanho_empresa"].value_counts()

tamanho_empresa
Media      129561
Grande       3574
Pequena       214
Name: count, dtype: int64

In [38]:
remoto = {
    0: 'Presencial',
    50: 'Hibrido',
    100: 'Remoto'
}

df["remoto"] = df["remoto"].replace(remoto)
display(df["remoto"].value_counts())

remoto
Presencial    105312
Remoto         27718
Hibrido          319
Name: count, dtype: int64

In [39]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Media
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Media
2,2025.0,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Media
3,2025.0,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Media
4,2025.0,Junior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Media

In [40]:
df.describe(include="object")

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Integral,Data Scientist,USD,US,Presencial,US,Media
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [41]:
df.describe()

                 ano       salario            usd
count  133339.000000  1.333490e+05  133349.000000
mean     2024.358770  1.632833e+05  157617.272098
std         0.680627  2.173860e+05   74288.363097
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060200e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000

# Aula 2 - Prepara√ß√£o e limpeza dos Dados

In [42]:
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [44]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,Media
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,Media
2,2025.0,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,Media
3,2025.0,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,Media
4,2025.0,Junior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,Media

In [45]:
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [46]:
df['ano'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [48]:
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,Integral,Product Manager,184500,USD,184500,US,Presencial,US,Media
59692,NaN,Pleno,Integral,Engineer,110000,USD,110000,DE,Presencial,DE,Media
59710,NaN,Junior,Integral,Data Scientist,208800,USD,208800,US,Presencial,US,Media
59759,NaN,Senior,Integral,Software Engineer,135000,USD,135000,US,Presencial,US,Media
59789,NaN,Senior,Integral,Engineer,112000,USD,112000,US,Presencial,US,Media
131000,NaN,Senior,Integral,Machine Learning Engineer,163800,USD,163800,US,Presencial,US,Media
131006,NaN,Senior,Integral,Data Analytics Manager,204500,USD,204500,US,Presencial,US,Media
133054,NaN,Junior,Integral,Data Scientist,40000,USD,40000,JP,Remoto,MY,Grande
133281,NaN,Pleno,Integral,Machine Learning Engineer,180000,PLN,46597,PL,Remoto,PL,Grande
133317,NaN,Pleno,Integral,Data Scientist,130000,USD,130000,US,Hibrido,US,Grande

In [57]:
import numpy as np

# Cria√ß√£o de um dataframe de teste para usar de exemplo
df_salarios = pd.DataFrame({
    'nome': ["Ana", "Bruno", "Carlos", "Daniele", "Val"],
    'salario': [4000, np.nan, 5000, np.nan, 100000]
})

# calcula a m√©dia salarial e substitui os nulos pela m√©dia e arredonda os valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))

df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

      nome   salario  salario_media  salario_mediana
0      Ana    4000.0        4000.00           4000.0
1    Bruno       NaN       36333.33           5000.0
2   Carlos    5000.0        5000.00           5000.0
3  Daniele       NaN       36333.33           5000.0
4      Val  100000.0      100000.00         100000.0

In [62]:
df_temperaturas = pd.DataFrame({
    "Dia": ["Segunda", "Ter√ßa", "Quarta", "Quinta", "Sexta", "S√°bado"],
    "Temperatura": [30, np.nan, np.nan, 28, 27, 30]
})

df_temperaturas["preenchido_bfill"] = df_temperaturas["Temperatura"].bfill()
df_temperaturas

       Dia  Temperatura  preenchido_bfill
0  Segunda         30.0              30.0
1    Ter√ßa          NaN              28.0
2   Quarta          NaN              28.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0
5   S√°bado         30.0              30.0

In [66]:
df_cidades = pd.DataFrame({
    'nome': ["Ana", "Bruno", "Carlos", "Daniele", "Val"],
    'cidade': ["S√£o Paulo", np.nan, "Curitiba", np.nan, "Bel√©m"]
})

df_cidades['cidade_preenchida'] = df_cidades["cidade"].fillna("N√£o informado")
display(df_cidades)

      nome     cidade cidade_preenchida
0      Ana  S√£o Paulo         S√£o Paulo
1    Bruno        NaN     N√£o informado
2   Carlos   Curitiba          Curitiba
3  Daniele        NaN     N√£o informado
4      Val      Bel√©m             Bel√©m